name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pod
        run: |
          pod install
      - name: Test
        run: |
          xcodebuild \
          -workspace SelfHostedRunner.xcworkspace \
          -scheme SelfHostedRunner \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator, name=iPhone 12' \
          test
