name: deploy_AppStore

# SECRETS needed:
### SSH_PRIVATE_KEY for Match Repo
### MATCH_PASS

on:

  push:
    branches: [ main ]

jobs:
        
  Build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.5.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
    # Set fetch-depth (default: 1) to get whole tree
      with:
        fetch-depth: 0

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
    - name: Bundle install
      run: |
        bundle install

    - name: Cache Pods
      uses: actions/cache@v2
      id: cocoapodCache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Install Pods Dependencies
      run: |
        bundle exec pod install
      shell: bash

    - name: Match AppStore
      run: |
        bundle exec fastlane syncAppStoreSigningCI
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}

    - name: Build App and Distibute to AppStore
      run: bundle exec fastlane build_and_upload_appstore_app