name: Secret Printout

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Print out Secret env for Demo
    runs-on: self-hosted
    
    steps:
      - name: Get data from Secret
        run: |
          echo $EXAMPLE
          echo $NON_EXISTING
        env:
          EXAMPLE: ${{ secrets.example }}
